services:
  server:
    image: express-server
    build: .
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/serverdb?schema=public
    ports:
      - 8080:8080
    networks:
      - internal-net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal-net

networks:
  internal-net:

volumes:
  pgdata: