services:
  server:
    image: ghcr.io/final-project-devops/back-end:master
    entrypoint: ["/bin/sh", "-c", "export DATABASE_URL=$$(cat /run/secrets/db_url) && ./entrypoint.sh"]
    ports:
      - 8080:8080
    networks:
      - internal-net
    secrets:
      - db_url
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    networks:
      - internal-net
    secrets:
      - postgres_user
      - postgres_password

secrets:
  postgres_user:
    external: true
  postgres_password:
    external: true
  db_url:
    external: true

networks:
  internal-net:
    driver: overlay,

volumes:
  pgdata: