name: "Build and Publsh Image to Dockerhub"
on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Build Docker Image from Main Branch"
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Checkout the Repository"
        uses: actions/checkout@v4

      - name: "Set Up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to docker.io"
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: "Build and Push Image"
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
