name: "Build and Publish Image to Dockerhub"
on:
  push:
    branches:
      - master

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: "Build Docker Image from Main Branch"
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Checkout the Repository"
        uses: actions/checkout@v4

      - name: "Set Up Docker Buildx"
        uses: docker/setup-buildx-action@v3

      - name: "Login to docker.io"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: "Extract Image Metadata"
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: "Build and Push Image"
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
